### ISSUE TITLE
Bring in new System of units

### ISSUE THREAD

**Issue by PatrickKibies** [linuxuser1/solar#2]
Length in 1e9 m (Gm)
Mass in 1e21 kg (Yg)
Time in 1e15s (Ps)

---> Gravitational constant is then 6,67408e13 (Gm^3/(Yg*Ps^2))

**Comment by KowalskiTheP** [comment]
The new unit system is established

**Comment by PatrickKibies** [comment]
Very nice job, Kowalski!
